import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { useActiveBatch } from '../hooks/useActiveBatch.js';
import { formatPaise } from '../lib/currency.js';
import { PageHeader } from '../components/layout/PageHeader.jsx';
import { EmptyState, ErrorState, LoadingState } from '../components/feedback/AsyncState.jsx';
import { StatusBadge } from '../components/feedback/StatusBadge.jsx';
import { resetAllData } from '../api/batchesApi.js';

const percent = (value) => value == null ? '—' : `${(value * 100).toFixed(1)}%`;
export function DashboardPage() {
  const active = useActiveBatch(); const [resetOpen, setResetOpen] = useState(false); const [confirmation, setConfirmation] = useState(''); const client = useQueryClient();
  const reset = useMutation({ mutationFn: resetAllData, onSuccess: async () => { localStorage.removeItem('settlewise-active-batch'); setResetOpen(false); setConfirmation(''); await client.invalidateQueries(); } });
  if (active.isPending) return <main><LoadingState label="Loading workspace" /></main>;
  if (active.isError) return <main><ErrorState error={active.error} retry={active.refetch} /></main>;
  if (!active.activeBatch) return <main><PageHeader eyebrow="Overview" title="Reconciliation dashboard" description="Measured settlement performance for your active batch." /><EmptyState title="No batches yet" detail="Create a batch and import settlement data to begin." action={<a className="button" href="/data-source">Upload or generate data</a>} /></main>;
  const batch = active.activeBatch; const counts = [{ name: 'matched', value: batch.statusCounts.matched }, { name: 'pending review', value: batch.statusCounts.pendingReview }, { name: 'unresolved', value: batch.statusCounts.unresolved }];
  const metrics = batch.metrics;
  return <main><PageHeader eyebrow="Overview" title="Reconciliation dashboard" description="Every figure below is loaded from the active batch on the server." actions={<><select aria-label="Active batch" value={batch.id} onChange={(event) => { active.selectBatch(event.target.value); location.reload(); }}>{active.batches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="danger secondary" onClick={() => setResetOpen(true)}>Reset all data</button></>} />
    <div className="batch-strip"><div><StatusBadge status={batch.status} /><strong>{batch.name}</strong></div><span>{batch.orderCount} orders · {batch.settlementRecordCount} settlement rows</span></div>
    <section className="kpi-grid"><article className="kpi"><span>Auto-match rate</span><strong>{percent(metrics.autoMatchRate)}</strong><small>Server-classified matches</small></article><article className="kpi"><span>Precision</span><strong>{percent(metrics.precision)}</strong><small>Correct automatic matches</small></article><article className="kpi"><span>Recall</span><strong>{percent(metrics.recall)}</strong><small>Eligible records recovered</small></article><article className="kpi"><span>Unexplained variance</span><strong>{metrics.unexplainedVariancePaise == null ? '—' : formatPaise(metrics.unexplainedVariancePaise)}</strong><small>Integer-paise server total</small></article></section>
    <section className="dashboard-grid"><article className="panel chart"><div><span className="eyebrow">Current distribution</span><h3>Match outcomes</h3></div>{counts.every((item) => item.value === 0) ? <EmptyState title="Not reconciled" detail="Run reconciliation to populate match outcomes." /> : <div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={counts} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={3}>{['#16856f', '#e6a23c', '#d45a53'].map((color) => <Cell key={color} fill={color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="legend">{counts.map((item) => <span key={item.name}><i className={item.name} />{item.name}: <strong>{item.value}</strong></span>)}</div></div>}</article><article className="panel"><span className="eyebrow">Processing proof</span><h3>Measured performance</h3><dl className="metric-list"><div><dt>Matching duration</dt><dd>{metrics.matchingDurationMs == null ? '—' : `${metrics.matchingDurationMs} ms`}</dd></div><div><dt>Manual review rate</dt><dd>{percent(metrics.manualReviewRate)}</dd></div><div><dt>Exception recall</dt><dd>{percent(metrics.exceptionRecall)}</dd></div><div><dt>False-match rate</dt><dd>{percent(metrics.falseMatchRate)}</dd></div></dl></article></section>
    {resetOpen && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><span className="eyebrow">Irreversible action</span><h3 id="reset-title">Reset all reconciliation data?</h3><p>This deletes every batch, order, settlement, match, explanation, review, and audit event. Your login is preserved.</p><label>Type <code>RESET ALL DATA</code> exactly<input autoFocus value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label>{reset.isError && <ErrorState error={reset.error} />}<div className="actions"><button className="secondary" onClick={() => setResetOpen(false)}>Cancel</button><button className="danger" disabled={confirmation !== 'RESET ALL DATA' || reset.isPending} onClick={() => reset.mutate(confirmation)}>{reset.isPending ? 'Resetting…' : 'Permanently reset'}</button></div></section></div>}
  </main>;
}
