import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { createBatch, fetchSettlements, generateOrders, reconcile, uploadSettlements } from '../api/batchesApi.js';
import { useActiveBatch } from '../hooks/useActiveBatch.js';
import { PageHeader } from '../components/layout/PageHeader.jsx';
import { ErrorState, LoadingState, SuccessBanner } from '../components/feedback/AsyncState.jsx';
import { StatusBadge } from '../components/feedback/StatusBadge.jsx';

export function DataSourcePage() {
  const active = useActiveBatch(); const queryClient = useQueryClient(); const [fallback, setFallback] = useState(null); const [success, setSuccess] = useState('');
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ['batches'] }); await active.refetch(); };
  const create = useMutation({ mutationFn: createBatch, onSuccess: async ({ data }) => { active.selectBatch(data.id); setSuccess('Batch created. Try the API import or upload a fallback CSV.'); await refresh(); }, onError: () => setSuccess('') });
  const apiImport = useMutation({ mutationFn: ({ id, input }) => fetchSettlements(id, input), onSuccess: async ({ data }) => { setFallback(null); setSuccess(`API import succeeded with ${data.recordCount} records.`); await refresh(); }, onError: (error) => { setFallback(error); setSuccess(''); } });
  const upload = useMutation({ mutationFn: ({ id, file }) => uploadSettlements(id, file), onSuccess: async ({ data }) => { setSuccess(`CSV fallback imported ${data.recordCount} records atomically.`); setFallback(null); await refresh(); } });
  const generate = useMutation({ mutationFn: ({ id, seed }) => generateOrders(id, { count: 150, seed: seed || undefined }), onSuccess: async ({ data }) => { setSuccess(`Generated ${data.orderCount} deterministic orders.`); await refresh(); } });
  const run = useMutation({ mutationFn: reconcile, onSuccess: async ({ data }) => { setSuccess(`Reconciliation completed for ${data.counts.total} orders.`); await refresh(); } });
  const busy = create.isPending || apiImport.isPending || upload.isPending || generate.isPending || run.isPending;
  if (active.isPending) return <main><LoadingState /></main>;
  return <main><PageHeader eyebrow="Data workflow" title="Upload & generate" description="Try Razorpay first, then visibly fall back to an atomically validated CSV if the provider is unavailable." />
    <SuccessBanner>{success}</SuccessBanner>{create.isError && <ErrorState error={create.error} />}
    <section className="workflow-grid"><article className="panel step"><span className="step-number">01</span><h3>Create a batch</h3><p>Choose the intended source. Counts and metrics remain authoritative on the server.</p><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ name: data.get('name'), sourceMode: data.get('sourceMode'), requestedCount: 150 }); }}><label>Batch name<input name="name" defaultValue="Demo reconciliation — 150 orders" maxLength="80" required /></label><label>Primary source<select name="sourceMode"><option value="api">Razorpay API</option><option value="csv">CSV fallback</option></select></label><button disabled={busy}>Create batch</button></form></article>
      <article className="panel step"><span className="step-number">02</span><h3>Import settlement recon</h3>{active.activeBatch ? <><div className="selected-batch"><StatusBadge status={active.activeBatch.status} /><strong>{active.activeBatch.name}</strong></div><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const date = new Date(data.get('date')); apiImport.mutate({ id: active.activeBatchId, input: { year: date.getFullYear(), month: date.getMonth() + 1, day: date.getDate() } }); }}><label>Recon date<input name="date" type="date" required /></label><button disabled={busy}>Try Razorpay API</button></form>{apiImport.isError && <div className="fallback-callout" role="alert"><strong>API unavailable — CSV fallback ready</strong><p>{fallback?.message}</p><code>{fallback?.code ?? 'RAZORPAY_UNAVAILABLE'}</code></div>}<form className="upload-form" onSubmit={(event) => { event.preventDefault(); const file = new FormData(event.currentTarget).get('file'); if (file?.size) upload.mutate({ id: active.activeBatchId, file }); }}><label>Razorpay-format CSV<input name="file" type="file" accept=".csv,text/csv" required /></label><button className="secondary" disabled={busy}>Upload CSV fallback</button></form>{upload.isError && <ErrorState error={upload.error} />}</> : <p className="muted">Create a batch to enable import controls.</p>}</article>
      <article className="panel step"><span className="step-number">03</span><h3>Generate & reconcile</h3><p>Generate exactly 150 deterministic orders after settlement records are imported.</p><form onSubmit={(event) => { event.preventDefault(); generate.mutate({ id: active.activeBatchId, seed: new FormData(event.currentTarget).get('seed') }); }}><label>Deterministic seed <small>(optional)</small><input name="seed" placeholder="demo-2026" /></label><button disabled={busy || !active.activeBatchId}>Generate 150 orders</button></form>{generate.isError && <ErrorState error={generate.error} />}<button className="run-button" disabled={busy || !active.activeBatchId} onClick={() => run.mutate(active.activeBatchId)}>{run.isPending ? 'Reconciling…' : 'Run reconciliation'}</button>{run.isError && <ErrorState error={run.error} />}</article></section>
  </main>;
}
