import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getRecords } from '../api/recordsApi.js';
import { downloadCsv } from '../lib/apiClient.js';
import { useActiveBatch } from '../hooks/useActiveBatch.js';
import { formatPaise } from '../lib/currency.js';
import { PageHeader } from '../components/layout/PageHeader.jsx';
import { EmptyState, ErrorState, LoadingState } from '../components/feedback/AsyncState.jsx';
import { StatusBadge } from '../components/feedback/StatusBadge.jsx';
import { Pagination } from '../components/tables/Pagination.jsx';
import { MatchDetails } from '../components/tables/MatchDetails.jsx';
import { getMatch } from '../api/reviewsApi.js';

export function RecordsPage() {
  const active = useActiveBatch(); const [filters, setFilters] = useState({ page: 1, pageSize: 20, status: '', case: '', search: '' }); const [exportError, setExportError] = useState(''); const [selectedMatchId, setSelectedMatchId] = useState(null);
  const query = useQuery({ queryKey: ['records', active.activeBatchId, filters], queryFn: () => getRecords(active.activeBatchId, filters), enabled: Boolean(active.activeBatchId), placeholderData: (previous) => previous });
  const detail = useQuery({ queryKey: ['match', selectedMatchId], queryFn: () => getMatch(selectedMatchId), enabled: Boolean(selectedMatchId) });
  async function exportRecords() { try { setExportError(''); const result = await downloadCsv(`/api/v1/batches/${active.activeBatchId}/export.csv`); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.fileName; link.click(); URL.revokeObjectURL(url); } catch (error) { setExportError(error.message); } }
  return <main><PageHeader eyebrow="Reconciliation ledger" title="Records" description="Server-filtered orders joined to their current match and primary settlement evidence." actions={<button disabled={!active.activeBatchId} onClick={exportRecords}>Export CSV</button>} />{exportError && <div className="banner error" role="alert">{exportError}</div>}
    {!active.activeBatchId ? <EmptyState title="No active batch" detail="Create a batch before browsing records." /> : <><form className="filters" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setFilters((value) => ({ ...value, page: 1, search: data.get('search') })); }}><label>Search<input name="search" defaultValue={filters.search} placeholder="Order, receipt or entity ID" /></label><label>Status<select value={filters.status} onChange={(event) => setFilters((value) => ({ ...value, page: 1, status: event.target.value }))}><option value="">All statuses</option><option value="matched">Matched</option><option value="pending_review">Pending review</option><option value="unresolved">Unresolved</option></select></label><label>Case<select value={filters.case} onChange={(event) => setFilters((value) => ({ ...value, page: 1, case: event.target.value }))}><option value="">All cases</option>{['normal','amount_mismatch','date_mismatch','missing_reference','duplicate_candidate','fee_mismatch','tax_mismatch','refund_mismatch','missing_settlement'].map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><button className="secondary">Apply</button></form>
    {query.isPending ? <LoadingState label="Loading records" /> : query.isError ? <ErrorState error={query.error} retry={query.refetch} /> : query.data.data.length === 0 ? <EmptyState title="No records found" detail="Adjust filters or complete the upload and generation workflow." /> : <><div className="table-wrap"><table><thead><tr><th>Order</th><th>Case</th><th>Gross</th><th>Expected net</th><th>Actual net</th><th>Variance</th><th>Confidence</th><th>Status</th><th>Details</th></tr></thead><tbody>{query.data.data.map((record) => <tr key={record.orderId}><td><strong>{record.merchantOrderId}</strong><small>{record.orderReceipt || 'No receipt'}</small></td><td>{record.generationCase.replaceAll('_', ' ')}</td><td>{formatPaise(record.grossAmountPaise)}</td><td>{formatPaise(record.expectedNetPaise)}</td><td>{record.match?.actualNetPaise == null ? '—' : formatPaise(record.match.actualNetPaise)}</td><td className={record.match?.variancePaise ? 'negative' : ''}>{record.match?.variancePaise == null ? '—' : formatPaise(record.match.variancePaise)}</td><td>{record.match ? `${record.match.confidenceScore}/100` : '—'}</td><td><StatusBadge status={record.match?.status} /></td><td>{record.match && <button className="secondary compact" onClick={() => setSelectedMatchId(record.match.id)}>View details</button>}</td></tr>)}</tbody></table></div><Pagination meta={query.data.meta} onPage={(page) => setFilters((value) => ({ ...value, page }))} /></>}
    {selectedMatchId && (detail.isPending ? <div className="drawer-backdrop"><section className="details-drawer"><LoadingState label="Loading match details" /></section></div> : detail.isError ? <div className="drawer-backdrop"><section className="details-drawer"><ErrorState error={detail.error} retry={detail.refetch} /><button className="secondary" onClick={() => setSelectedMatchId(null)}>Close</button></section></div> : <MatchDetails match={detail.data.data} onClose={() => setSelectedMatchId(null)} />)}</>}</main>;
}
