import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { approveMatch, explainMatch, getMatch, getReviewQueue, manualLink, rejectMatch } from '../api/reviewsApi.js';
import { useActiveBatch } from '../hooks/useActiveBatch.js';
import { formatPaise } from '../lib/currency.js';
import { PageHeader } from '../components/layout/PageHeader.jsx';
import { EmptyState, ErrorState, LoadingState, SuccessBanner } from '../components/feedback/AsyncState.jsx';
import { StatusBadge } from '../components/feedback/StatusBadge.jsx';
import { Pagination } from '../components/tables/Pagination.jsx';

export function ReviewQueuePage() {
  const active = useActiveBatch(); const client = useQueryClient(); const [page, setPage] = useState(1); const [selected, setSelected] = useState(null); const [success, setSuccess] = useState('');
  const queue = useQuery({ queryKey: ['review-queue', active.activeBatchId, page], queryFn: () => getReviewQueue(active.activeBatchId, { page, pageSize: 20 }), enabled: Boolean(active.activeBatchId) });
  const detail = useQuery({ queryKey: ['match', selected], queryFn: () => getMatch(selected), enabled: Boolean(selected) });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ['review-queue'] }); await client.invalidateQueries({ queryKey: ['records'] }); await client.invalidateQueries({ queryKey: ['batches'] }); setSelected(null); };
  const decision = useMutation({ mutationFn: ({ action, matchId, note, settlementRecordId }) => action === 'approve' ? approveMatch(matchId, note) : action === 'reject' ? rejectMatch(matchId, note) : manualLink(matchId, settlementRecordId, note), onSuccess: async (_, input) => { setSuccess(`${input.action.replace('_', ' ')} recorded with review and audit history.`); await refresh(); } });
  const explain = useMutation({ mutationFn: explainMatch, onSuccess: async () => { setSuccess('Advisory explanation refreshed. Financial match fields were not changed.'); await client.invalidateQueries({ queryKey: ['match', selected] }); } });
  return <main><PageHeader eyebrow="Human control" title="Review queue" description="Compare deterministic candidate evidence first. AI prose is displayed separately and remains advisory." /><SuccessBanner>{success}</SuccessBanner>
    {!active.activeBatchId ? <EmptyState title="No active batch" detail="Create and reconcile a batch to populate the queue." /> : queue.isPending ? <LoadingState label="Loading review queue" /> : queue.isError ? <ErrorState error={queue.error} retry={queue.refetch} /> : queue.data.data.length === 0 ? <EmptyState title="Queue is clear" detail="There are no pending-review records in this batch." /> : <div className="review-layout"><section className="queue-list">{queue.data.data.map((record) => <button className={`queue-card ${selected === record.match.id ? 'selected' : ''}`} key={record.match.id} onClick={() => setSelected(record.match.id)}><div><strong>{record.merchantOrderId}</strong><StatusBadge status={record.match.status} /></div><span>{formatPaise(record.expectedNetPaise)} expected · {record.match.confidenceScore}/100</span><small>{record.match.reasonCodes.join(' · ')}</small></button>)}<Pagination meta={queue.data.meta} onPage={setPage} /></section><section className="review-detail">{!selected ? <EmptyState title="Select a record" detail="Choose a queue item to inspect candidate evidence and act." /> : detail.isPending ? <LoadingState label="Loading evidence" /> : detail.isError ? <ErrorState error={detail.error} retry={detail.refetch} /> : <ReviewDetail match={detail.data.data} mutation={decision} explain={explain} />}</section></div>}
  </main>;
}

function ReviewDetail({ match, mutation, explain }) {
  const [note, setNote] = useState(''); const candidates = match.deterministicEvidence.rankedCandidates ?? [];
  return <div><div className="detail-heading"><div><span className="eyebrow">Deterministic result</span><h3>{match.order.merchantOrderId}</h3></div><strong className="score">{match.confidenceScore}<small>/100</small></strong></div><div className="evidence-panel"><h4>Authoritative evidence</h4><div className="evidence-summary"><span>Expected {formatPaise(match.expectedNetPaise)}</span><span>Actual {match.actualNetPaise == null ? '—' : formatPaise(match.actualNetPaise)}</span><span>Variance {match.variancePaise == null ? '—' : formatPaise(match.variancePaise)}</span></div><div className="reason-list">{match.reasonCodes.map((code) => <code key={code}>{code}</code>)}</div><div className="candidates">{candidates.map((candidate, index) => <label className="candidate" key={candidate.settlementRecordId}><input type="radio" name="candidate" value={candidate.settlementRecordId} defaultChecked={index === 0} /><span><strong>Candidate {index + 1} · {candidate.score}/100</strong><small>{candidate.entityId} · {candidate.source}</small><em>{Object.entries(candidate.checks ?? {}).map(([key, value]) => `${key}: ${value ? 'pass' : 'fail'}`).join(' · ')}</em></span></label>)}</div></div>
    <div className="ai-panel"><div><span className="eyebrow">AI explanation · advisory only</span><h4>{match.aiExplanation?.category?.replaceAll('_', ' ') ?? 'Not generated'}</h4></div>{match.aiExplanation ? <><p>{match.aiExplanation.summary}</p><small>Suggested next step: {match.aiExplanation.recommendedAction}</small><code>{match.aiExplanation.status}{match.aiExplanation.errorCode ? ` · ${match.aiExplanation.errorCode}` : ''}</code></> : <p>No explanation stored. Deterministic evidence remains fully available.</p>}<button className="secondary" disabled={explain.isPending} onClick={() => explain.mutate(match.id)}>{explain.isPending ? 'Generating…' : 'Generate / retry explanation'}</button>{explain.isError && <ErrorState error={explain.error} />}</div>
    <div className="decision-panel"><label>Review note<textarea value={note} maxLength="500" onChange={(event) => setNote(event.target.value)} placeholder="Optional rationale for the audit history" /></label>{mutation.isError && <ErrorState error={mutation.error} />}<div className="actions"><button disabled={mutation.isPending} onClick={() => mutation.mutate({ action: 'approve', matchId: match.id, note })}>Approve top candidate</button><button className="danger" disabled={mutation.isPending} onClick={() => mutation.mutate({ action: 'reject', matchId: match.id, note })}>Reject</button><button className="secondary" disabled={mutation.isPending || !candidates.length} onClick={() => { const chosen = document.querySelector('input[name="candidate"]:checked')?.value; if (chosen) mutation.mutate({ action: 'manual_link', matchId: match.id, settlementRecordId: chosen, note }); }}>Manual link selected</button></div></div></div>;
}
