export const REASON_CODES = Object.freeze({
  EXACT_ORDER_ID: 'EXACT_ORDER_ID',
  EXACT_ORDER_RECEIPT: 'EXACT_ORDER_RECEIPT',
  EXACT_GROSS_AMOUNT: 'EXACT_GROSS_AMOUNT',
  DATE_WITHIN_TOLERANCE: 'DATE_WITHIN_TOLERANCE',
  FORMULA_AGREES: 'FORMULA_AGREES',
  AMBIGUOUS_CANDIDATES: 'AMBIGUOUS_CANDIDATES',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  DATE_OUTSIDE_TOLERANCE: 'DATE_OUTSIDE_TOLERANCE',
  MISSING_REFERENCE: 'MISSING_REFERENCE',
  NO_CANDIDATE: 'NO_CANDIDATE',
  SETTLEMENT_ALREADY_LINKED: 'SETTLEMENT_ALREADY_LINKED',
  FEE_MISMATCH: 'FEE_MISMATCH',
  TAX_MISMATCH: 'TAX_MISMATCH',
  REFUND_MISMATCH: 'REFUND_MISMATCH',
  AI_EXPLANATION_FAILED: 'AI_EXPLANATION_FAILED'
});

